server:
  port: 8088

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.140:8761/eureka/,http://192.168.0.141:8761/eureka/,http://192.168.0.142:8761/eureka/

